/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import System.Jugador;
import System.Tablero;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author avalo
 */
public class panelJuego extends javax.swing.JPanel {

    /**
     * Creates new form panelJuego
     */
    private static PanelTablero tablero;
    private static Panel fondoPanel;
    private Tablero tableroLogico;
    
    public panelJuego() {
        initComponents();
        initTablero();
        fondoPanel=new Panel("/icons/agua (1).jpg");
        fondoPanel.setBounds(0, 0, 800, 600);
        fondoPanel.setVisible(true);
        add(fondoPanel);
        mensajeTiro.setVisible(false);
        NumBarcos.setVisible(true);
        nBarco.setVisible(true);
        muestraIntentos.setVisible(true);
        nIntentos.setVisible(true);
    }
    
    public void setTableroLogico(Tablero tableroLogico){
        this.tableroLogico=tableroLogico;
    }
    
    public void initTablero(){
        tablero=new PanelTablero();
        tablero.setBounds(50, 50, 600, 400);
        //tablero.setBackground(new java.awt.Color(255, 255, 255));
        tablero.setVisible(true);
        
        add(tablero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shootBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        coordenadaX = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        coordenadaY = new javax.swing.JComboBox<>();
        mensajeTiro = new javax.swing.JLabel();
        NumBarcos = new javax.swing.JLabel();
        nBarco = new javax.swing.JLabel();
        muestraIntentos = new javax.swing.JLabel();
        nIntentos = new javax.swing.JLabel();
        BotonSalida = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        shootBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/objetivo (2).png"))); // NOI18N
        shootBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FIRE!!", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Stencil", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        shootBtn.setContentAreaFilled(false);
        shootBtn.setDoubleBuffered(true);
        shootBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");

        coordenadaX.setMaximumRowCount(10);
        coordenadaX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        coordenadaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordenadaXActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Y");

        coordenadaY.setMaximumRowCount(10);
        coordenadaY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        mensajeTiro.setFont(new java.awt.Font("Lato Black", 0, 24)); // NOI18N
        mensajeTiro.setForeground(new java.awt.Color(255, 255, 255));

        NumBarcos.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        NumBarcos.setForeground(new java.awt.Color(255, 255, 255));
        NumBarcos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumBarcos.setText("Barcos Hundidos: ");

        nBarco.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        nBarco.setForeground(new java.awt.Color(255, 255, 255));
        nBarco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nBarco.setText("0");

        muestraIntentos.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        muestraIntentos.setForeground(new java.awt.Color(255, 255, 255));
        muestraIntentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        muestraIntentos.setText("Intentos:");

        nIntentos.setFont(new java.awt.Font("Lato Black", 0, 18)); // NOI18N
        nIntentos.setForeground(new java.awt.Color(255, 255, 255));
        nIntentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nIntentos.setText("10");

        BotonSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/flecha-hacia-atras.png"))); // NOI18N
        BotonSalida.setBorderPainted(false);
        BotonSalida.setContentAreaFilled(false);
        BotonSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(147, 147, 147)
                        .addComponent(jLabel2)
                        .addContainerGap(464, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(coordenadaX, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(coordenadaY, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mensajeTiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addComponent(shootBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addComponent(NumBarcos, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addComponent(nBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(muestraIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(NumBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(muestraIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nIntentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shootBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coordenadaX, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coordenadaY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mensajeTiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        shootBtn.getAccessibleContext().setAccessibleName("disparaBtn");
    }// </editor-fold>//GEN-END:initComponents

    private void shootBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootBtnActionPerformed
        // TODO add your handling code here:
        int op, x, y;
        x=Integer.parseInt(coordenadaX.getSelectedItem().toString());
        y=Integer.parseInt(coordenadaY.getSelectedItem().toString());
        op=tableroLogico.checarCasilla(x, y, VentanaJuego.getJugador());
        mensajeTiro.setVisible(true);
        switch(op){
            case 0:
                mensajeTiro.setVisible(false);
                JOptionPane.showMessageDialog(null, "Ya has seleccionado esa casilla anteriormente");
                break;
            case 1:
                tablero.setColor(x, y, Color.RED);
                 mensajeTiro.setText("  Has acertado!!");
                break;
            case 2:
                tablero.setColor(x, y, Color.BLUE);
                 mensajeTiro.setText("  Has fallado!!");
                break;
            default:
                break;
        }
        NumBarcos.setText("Barcos Hundidos:");
        nBarco.setText(""+VentanaJuego.getJugador().getBarcosHundidos());
        muestraIntentos.setText("Intentos:");
        nIntentos.setText(""+VentanaJuego.getJugador().getIntentos());
        
        if(VentanaJuego.getJugador().getBarcosHundidos()==10 || VentanaJuego.getJugador().getIntentos()==0)
            
            JOptionPane.showMessageDialog(null, "Fin de partida");
           
    }//GEN-LAST:event_shootBtnActionPerformed

    private void coordenadaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordenadaXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coordenadaXActionPerformed

    private void BotonSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalidaActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "Se perdera tu progreso si sales\n ¿Deseas continuar?" );
        if (respuesta == 0){
            VentanaJuego.getPnlMenu().setVisible(true);
            VentanaJuego.getPnlJuego().setVisible(false);
        }
    }//GEN-LAST:event_BotonSalidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalida;
    private javax.swing.JLabel NumBarcos;
    private javax.swing.JComboBox<String> coordenadaX;
    private javax.swing.JComboBox<String> coordenadaY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mensajeTiro;
    private javax.swing.JLabel muestraIntentos;
    private javax.swing.JLabel nBarco;
    private javax.swing.JLabel nIntentos;
    private javax.swing.JButton shootBtn;
    // End of variables declaration//GEN-END:variables
}
