/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import System.Jugador;
import System.Tablero;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author avalo
 */
public class panelJuego extends javax.swing.JPanel {

    /**
     * Creates new form panelJuego
     */
    private static PanelTablero tablero;
    private static Panel fondoPanel;
    private Tablero tableroLogico;
    private Jugador jugador;
    
    public panelJuego() {
        initComponents();
        initTablero();
        fondoPanel=new Panel("/icons/fondoJuego.jpeg");
        fondoPanel.setBounds(0, 0, 800, 600);
        fondoPanel.setVisible(true);
        add(fondoPanel);
        mensajeTiro.setVisible(false);
    }
    
    public void setTableroLogico(Tablero tableroLogico){
        this.tableroLogico=tableroLogico;
    }
    
    public void setJugador(Jugador jugador){
        this.jugador=jugador;
    }
    
    public void initTablero(){
        tablero=new PanelTablero();
        tablero.setBounds(50, 50, 600, 400);
        //tablero.setBackground(new java.awt.Color(255, 255, 255));
        tablero.setVisible(true);
        
        add(tablero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shootBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        coordenadaX = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        coordenadaY = new javax.swing.JComboBox<>();
        mensajeTiro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        shootBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/objetivo (2).png"))); // NOI18N
        shootBtn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SHOT!", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Stencil", 1, 12))); // NOI18N
        shootBtn.setContentAreaFilled(false);
        shootBtn.setDoubleBuffered(true);
        shootBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setText("X");

        coordenadaX.setMaximumRowCount(10);
        coordenadaX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        coordenadaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coordenadaXActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel2.setText("Y");

        coordenadaY.setMaximumRowCount(10);
        coordenadaY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(coordenadaX, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(coordenadaY, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mensajeTiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addComponent(shootBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(447, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(shootBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(coordenadaX)
                            .addComponent(coordenadaY, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(mensajeTiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        shootBtn.getAccessibleContext().setAccessibleName("disparaBtn");
    }// </editor-fold>//GEN-END:initComponents

    private void shootBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootBtnActionPerformed
        // TODO add your handling code here:
        int op, x, y;
        x=Integer.parseInt(coordenadaX.getSelectedItem().toString());
        y=Integer.parseInt(coordenadaY.getSelectedItem().toString());
        op=tableroLogico.checarCasilla(x, y, jugador);
        
        switch(op){
            case 0:
                JOptionPane.showMessageDialog(null, "Ya has seleccionado esa casilla anteriormente");
                break;
            case 1:
                tablero.setColor(x, y, Color.RED);
                break;
            case 2:
                tablero.setColor(x, y, Color.BLUE);
                break;
            default:
                break;
        }
        
        if(jugador.getBarcosHundidos()==10 || jugador.getIntentos()==0)
            JOptionPane.showMessageDialog(null, "Fin de partida");
           
    }//GEN-LAST:event_shootBtnActionPerformed

    private void coordenadaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coordenadaXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coordenadaXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> coordenadaX;
    private javax.swing.JComboBox<String> coordenadaY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mensajeTiro;
    private javax.swing.JButton shootBtn;
    // End of variables declaration//GEN-END:variables
}
