/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.battleship;

/**
 *
 * @author avalo
 */
public class panelRegistro extends javax.swing.JPanel {

    /**
     * Creates new form panelRegistro
     */
    public panelRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birthdate = new javax.swing.JFormattedTextField();
        txtFieldName = new javax.swing.JTextField();
        signinBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        birthdate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de nacimiento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Stencil", 1, 36))); // NOI18N
        birthdate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy/MM/dd"))));
        birthdate.setText("yyyy/mm/dd");
        birthdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        birthdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdateActionPerformed(evt);
            }
        });
        add(birthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 458, 72));

        txtFieldName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFieldName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Stencil", 1, 36))); // NOI18N
        add(txtFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 331, -1));

        signinBtn.setText("Entrar");
        signinBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        signinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinBtnActionPerformed(evt);
            }
        });
        add(signinBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 160, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void birthdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdateActionPerformed

    private void signinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtnActionPerformed
        // TODO add your handling code here: DEBE LLEVAR A MENU
        //CHECA EN BASE DE DATOS SI ESTA EL JUGADOR, SINO LO REGISTRA Y TIENE QUE GUARDARSE EN LA VARIABLE JUGADOR.
        VentanaJuego.getPnlRegistro().setVisible(false);
        VentanaJuego.getPnlMenu().setVisible(true);
    }//GEN-LAST:event_signinBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField birthdate;
    private javax.swing.JButton signinBtn;
    private javax.swing.JTextField txtFieldName;
    // End of variables declaration//GEN-END:variables
}
